version: '3.8'
services:
  db_reminder:
    container_name: db_reminder
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
    env_file:
      - .env
    image: postgres:13.3
  bot:
    build:
        context: .
        dockerfile: Dockerfile-bot