FROM golang:latest

WORKDIR /telegram_bot_reminder

# Download dependencies
COPY go.mod go.sum ./
RUN go mod download

# Build the app
COPY . ./
RUN go build -o main cmd/main.go

EXPOSE 8081

# Sleep for two seconds to give database time to start
CMD ["sh", "-c", "sleep 2 && ./main"]